### ISSUE TITLE
NodeJS application with use of Mermaid

### ISSUE THREAD

**Issue by brunolnetto** [mermaid-js/api-integration-ex#12]
Hi,

I am a pure NodeJS user. I would like to render a graph from my library [dot-quiver](https://github.com/dot-quiver/dot-quiver-api/blob/main/data-structures/graph/Graph.js) with your library. However, I am not familiar with Frontend concepts like "document" and "render".  In NodeJS, I send a JSON payload in response to some GET/POST request.

May you explain how to reproduce it?

**Comment by sidharthv96** [comment]
You can see how the mermaid cli project achieves it with the use of pupeteer.
https://github.com/mermaid-js/mermaid-cli

**Comment by brunolnetto** [comment]
I am grateful for your answer.
